\c studios_dev;

INSERT INTO studios (name, address, zipcode, city, state, phone_number, email, website_url, instagram_handle, description, specialization, offers_group, offers_mat, offers_reformer, offers_duets, offers_privates, offers_membership, offers_new_client_deal, is_black_owned)

VALUES (
  'Fringe Pilates',
  '1417 Nostrand Ave',
  11226,
  'Brooklyn',
  'NY',
  '(347) 201-3426',
  'fringepilatesbk@gmail.com',
  'https://www.fringepilates.com/',
  '@fringepilates',
  'If you are tired of feeling alone in your fitness classes or left out by your instructors, then you`re in the right place. 
  Here, we know that all bodies are Pilates bodies. It`s not about getting snatched or body shaming yourself into change.',
  'General Pilates',
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true
),

('Pilates BKLYN',
'1067 Manhattan Ave',
 11222,
 'Brooklyn',
 'NY',
'(347) 916-0887',
'info@pilatesbklyn.com',
'https://www.pilatesbklyn.com/',
'@pilatesbklyn',
' No matter your skill level, we have the perfect class for you to feel confident, challenged and motivated every time you come in.',
  'Rooftop Classes',
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  false
),

('Riverdale Pilates',
'3333 Henry Hudson Pkwy W # 5',
'10463',
'Bronx',
'NY',
'(917) 426-9156',
'info@riverdalepilates.net',
'http://riverdalepilates.net/',
null,
'We uphold Joseph Pilates` original vision: our passion is to help people feel great. We combine principles of both classical and contemporary Pilates to address clients of all needs across all spectrums of wellness.',
'Privates & Duets',
false,
false,
true,
true,
true,
false,
true,
false),

('Compass Pilates',
'3755 Henry Hudson Pkwy W',
10463,
'Bronx',
'NY',
'(646) 385-0623',
'info@compasspilatesny.com',
'https://www.compasspilatesny.com/',
'@compasspilatesny',
'With twenty years of experience and a great passion to utilizing the Pilates method to help people develop awareness of their own bodies, we will help you find the way to your body!',
'{Stroller Pilates, Dancer Pilates}',
true,
true,
false,
false,
true,
false,
true,
false),


('East River Pilates',
'235 S 1st St',
11211,
'Brooklyn',
'NY',
null,
'hello@eastriverpilates.com',
'https://eastriverpilates.com/',
'@eastriverpilates',
'Our mission is to share the life changing benefits of Pilates with all people, in Brooklyn, and beyond. How do we do it? We combine the world`s best contemporary feel-good Pilates workouts with a focus on form, function, and flow, and the support of an inclusive and celebratory community.',
'{Prenatal, Postnatal}',
true,
true,
true,
true,
true,
true,
true,
false
),

('Long Core Pilates',
'16 Burnside Ave',
10302,
'Staten Island',
'NY',
'(347) 272-6173',
'christine@longcorepilates.com',
'https://longcorepilates.com/contact-us/',
'@longcorepilates',
'We provide the direction that clients need to achieve a mind-body connection, resulting in a highly effective Pilates practice. Our methods aim to strengthen the core, improve stability and mobility, and encourage mindful movement to enrich all aspects of a healthy lifestyle and overall physicality.',
'Bodhi Suspension',
true,
true,
true,
true,
true,
true,
true,
false
),
('Pilates Staten Island',
'1231 Bay Street',
10305,
'Staten Island',
'NY',
'718-273-2400',
'mail@pilatesstatenisland.com',
'https://www.pilatesstatenisland.com/',
null,
'At Pilates Staten Island it is our mission to bring each client on a transformational physical and personal journey.  We want to convey that Contrology (Pilates) is much more than a “workout”.  We strive to maintain a nurturing and eductional environment where each client, regardless of whether they are in a private lesson or small mat class, receives an experience in their own personal movement.',
'digital workouts',
false,
true,
true,
true,
true,
true,
false,
false),

('Spencer Pilates Arts',
'108-12 72nd Ave',
11375,
'Queens',
'NY',
'718-261-0596',
null,
'www.spencerpilatesarts.com',
'@spencerpilates',
'We specialize in group and individual instruction, teaching mat and machine exercises designedd by Joseph Pilates.',
'{Cardio Pilates, Pregnancy Pilates}',
true,
true,
true,
true,
true,
false,
false,
false
);  




